### ISSUE TITLE
Confused about to_data(code, var, output)

### ISSUE THREAD

**Issue by AjayTalati** [wojciechz/learning_to_execute#2]
Hi Wojciech,

I wonder if you can help me? 

I've been working through the code for a few days, but I'm still confused about [line 42](https://github.com/wojciechz/learning_to_execute/blob/master/data.lua#L42) 

`table.insert(x, symbolsManager:get_symbol_idx(output:byte(j)))`

in `data.lua`.  It seems as though this line gives the network the 'answer/output' to the program which is the input on [line 39](https://github.com/wojciechz/learning_to_execute/blob/master/data.lua#L39)? I thought maybe it should be,

`for j = 1, #output do`
 `table.insert(x, 0)`
 `table.insert(y, symbolsManager:get_symbol_idx(output:byte(j)))`
 `end`

I'm still running experiments to see if the above change makes sense - that is, the code still learns. I could not find any part of the paper which explaines line 42, maybe I over looked something, or did not understand it?

If it is correct is there any chance you could explain a little what [line 42](https://github.com/wojciechz/learning_to_execute/blob/master/data.lua#L42) does?

Kind regards,

Aj

**Comment by wojzaremba** [comment]
This is so called teacher force. Out task is to predict entire sequence of
symbols, e.g. abcd. Let's say that at the first step model predicted q. We
still provide information that a is the correct answer on the first
position. Then model is about to predict next symbol given previous correct
answer given by the teacher.

x contains input and correct answers ofsetted by 1 in compare to y.

**Comment by AjayTalati** [comment]
Thank you very much :+1: that helps a lot :)

I'm just adapting the code at the moment to reproduce your results on the memorization task - it's a bit easier to understand than the full program evaluation task. 

I'm getting very good results using teacher forcing, inverting and doubling :+1: It's very impressive :+1: 

PS - Maybe the title on [page 10](http://arxiv.org/pdf/1410.4615v3.pdf), should be 'ADDITIONAL RESULTS ON THE PROGRAM EVALUATION PROBLEM' ?
